///////////////////////////////////////////////
//*-----------------------------------------*//
//| Auto-Generated by the Core Engine       |//
//| Direct modifications may be overwritten |//
//*-----------------------------------------*//
///////////////////////////////////////////////
#include "Core.h"


// ****************************************************************
// project settings
const coreChar* const CoreApp::Settings::Name                       = "Core Application";
const coreChar* const CoreApp::Settings::IconPath                   = "data/textures/game_icon.png";
const coreChar* const CoreApp::Settings::CursorPath                 = "data/textures/default_cursor.png";
const coreUint8       CoreApp::Settings::RenderBuffer::DepthSize    = 24u;
const coreUint8       CoreApp::Settings::RenderBuffer::StencilSize  = 8u;
const coreBool        CoreApp::Settings::RenderBuffer::AlphaChannel = true;
const coreBool        CoreApp::Settings::RenderBuffer::DoubleBuffer = true;
const coreBool        CoreApp::Settings::RenderBuffer::StereoRender = false;


// ****************************************************************
// setup the application
void CoreApp::Setup()
{

}